name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: us-east-2
  CONTAINER_NAME: example-app

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - uses: aws-actions/configure-aws-credentials@v1
      - name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
